development: &development
  adapter: sqlite3
  encoding: unicode
  database: testapp_development
  pool: 5
  username: 
  password: 
  host: localhost
  min_messages: WARNING

test:
  database: testapp_test
  <<: *development
